birthday_date = input("Give me your birthdate in format 'DD/MM/YYYY': ").strip().split("/")
leap_year = not int(birthday_date[2]) % 4 and (not int(birthday_date[2]) % 400 or int(birthday_date[2]) % 100)
age = 2022 - int(birthday_date[2])
print(f"  {'_' * (6 - int((age % 10)/2))}{'i'* (age % 10)}{'_' * (6 - int((age % 10)/2))}")
print("  |:H:a:p:p:y:|")
print("__|___________|__")
print("|^^^^^^^^^^^^^^^^^|")
print("|:B:i:r:t:h:d:a:y:|")
print("|                 |")
print("~~~~~~~~~~~~~~~~~~~")
if leap_year:
    print(f"  {'_' * (6 - int((age % 10) / 2))}{'i' * (age % 10)}{'_' * (6 - int((age % 10) / 2))}")
    print("  |:H:a:p:p:y:|")
    print("__|___________|__")
    print("|^^^^^^^^^^^^^^^^^|")
    print("|:B:i:r:t:h:d:a:y:|")
    print("|                 |")
    print("~~~~~~~~~~~~~~~~~~~")
